### ISSUE TITLE
Motivation behind SiLU(x) as a basis function

### ISSUE THREAD

**Issue by LarsDoorenbos** [KindXiaoming/pykan#128]
Thanks for the great work!

I'm curious what the motivation behind using SiLU(x) as a basis function is. SiLU would set any negative input to practically zero, thus destroying the residual connection, which seems counter-intuitive to me. 

Could you provide some intuition on why SiLU is used and how it compares to using, e.g., the identity function for b(x)? And did you try other basis functions?

On another note, from equation 2.10 in the paper (ϕ(x) = w (b(x) + spline(x))), it seems w is a single scalar, however from the code, two separate parameters are used:

https://github.com/KindXiaoming/pykan/blob/116f399af89373862917a8b71fe4442727b067e7/kan/KANLayer.py#L176

I guess having two separate parameters makes sense so that the residual connection has an individual learned component. Did you try both ways?

**Comment by LarsDoorenbos** [comment]
Thanks!

**Comment by j93hahn** [comment]
@chrico-bu-uab can you share the plot here? I see a `severity.png` file in your fork but am not sure if that is the plot you're referring to

**Comment by chrico-bu-uab** [comment]
That is the file (it's too big to post here so I posted just a subset of the edges).

![some_edges](https://github.com/KindXiaoming/pykan/assets/29983523/2b037914-1785-46bf-aaab-79fbf4208493)

It may not be quite as bad as I thought, but a lot of them do have a similar shape to SiLU and it did just produce lines when I swapped out SiLU for identity on my data (I would need to recreate that image). It jumped out at me when I saw a particular node with just SiLU curves, but that turned out to be a categorical node, which may or may not be the reason.

I'm updating my fork with some improvements to my code and a draft of an example notebook. It appears that adding linear layers and/or using categorical embeddings actually sort of works (at least on the slightly complicated toy problem I developed) and doesn't just produce lines/SiLU curves. I may have prematurely jumped to the conclusion that adding those things necessarily ruins the model, though I'm still not sure what's up with my data.

Sorry for any confusion that I might be generating.
