### ISSUE TITLE
help! there is a problem here! cell 12 of hellokan.ipynb, detail:RuntimeError: false INTERNAL ASSERT FAILED at "C:... please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library.

### ISSUE THREAD

**Issue by BinGnadenlos** [KindXiaoming/pykan#181]

**Comment by KindXiaoming** [comment]
maybe related to #179

**Comment by Stealeristaken** [comment]
What is the CPU/HPU  that you use during implementing pytorch? I saw in the issues that someone claim that there might be a problem with Apple Silicon devices. #199

**Comment by BinGnadenlos** [comment]
> What is the CPU/GPU that you use during implementing pytorch? I saw in the issues that someone claim that there might be a problem with Apple Silicon devices. #199

sorry for the late response, I use the Cuda.

**Comment by KindXiaoming** [comment]
Hi, in this case, it looks like the network fails to learn only one hidden neurons, but there are two duplicate neurons. You could try increase `lamb_entropy`, `lamb` or change another random seed.

This error "RuntimeError: stack expects a non-empty TensorList" means the threshold is set too large such that all neurons are pruned away.

**Comment by danjdowling** [comment]
RuntimeError: false INTERNAL ASSERT FAILED at "C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\aten\src\ATen\native\BatchLinearAlgebra.cpp":1540, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library..

I have the same issue, I will try on different datasets and report

**Comment by danjdowling** [comment]
i received this same error when training on a dataset i had generated for the purposes of classification, the inputs and oututs were so similar the model would need very little training. I followed this process and was able to generate outputs until In [11].
https://github.com/KindXiaoming/pykan/blob/master/hellokan.ipynb

I have now used data which involves learning and the issue has gone away. So possibly this was due to the data that was inputted and the lack of learning required.
