### ISSUE TITLE
How to do cross validation using KAN?

### ISSUE THREAD

**Issue by Yagnik12599** [KindXiaoming/pykan#234]
Any idea on how I can do cross validation (like KFold) using KAN model?

Thanks

**Comment by seyidcemkarakas** [comment]
Well, basically you can seperate your data into 2 part => 1 training 2 testing.  With training part, you can build K-Fold structure manually. Also you can add HP Optimization part because as you know KAN requires lots of Hyperparameters like grid, k, width etc. . By getting scores, you can store all performance metrics and corresponding hyperparameters and then you can build you final model.
