### ISSUE TITLE
'KAN' module object is not callable

### ISSUE THREAD

**Issue by SalmaMohamedElsayed** [KindXiaoming/pykan#304]
In this tutorial notebook: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Example_3_classfication.ipynb, when I run this line
model = KAN(width=[2,1], grid=3, k=3)
I face this error: typeerror: 'module' object is not callable

**Comment by FLjv77** [comment]
Install via => pip install git+https://github.com/KindXiaoming/pykan.git

Run the flowing code and face this error  "NameError: name 'KAN' is not defined"

from kan import *
model = KAN(width=[2,5,1], grid=5, k=3, seed=0)

This error appears after the last update project because i had no such error hours ago.

**Comment by pkpro** [comment]
Same here, and it does not matter if you install it from github or PyPy, the version in PyPy is also updated to 0.1.1.

**Comment by Chenhubget** [comment]
SO

**Comment by SalmaMohamedElsayed** [comment]
I installed it using this method but also it did not work and the same error appears

**Comment by Renato5597** [comment]
Try to change this:
from kan import KAN
to this:
from kan.KAN import KAN

**Comment by KindXiaoming** [comment]
Major update today. Please try update to 0.2.0 version. Thanks!
