### ISSUE TITLE
Training on GPU doesn't work

### ISSUE THREAD

**Issue by viktor-ktorvi** [KindXiaoming/pykan#5]
Hi, when training on GPU, the data is on GPU, while the layers are on CPU. One of the reasons is that the constructor of KAN takes in an arg called 'device' but doesn't use it. For example, it should be passed into KANLayer in [this line](https://github.com/KindXiaoming/pykan/blob/6aed4d78c687601b018fa750bdb0fd95a7080c11/kan/KAN.py#L138) but is not.

Another thing is that setting `model.to(device)` doesn't do anything, as far as I can tell.

**Comment by viktor-ktorvi** [comment]
There are also a bunch of functions that take in `device` but don't use it where it's needed.

**Comment by viktor-ktorvi** [comment]
Sorry for spamming issues here, however, [this](https://github.com/KindXiaoming/pykan/blob/6aed4d78c687601b018fa750bdb0fd95a7080c11/kan/__init__.py#L4) setting of the dtype explicitly to `float64` is also obviously an issue. I understand that this is fine for the use case of getting results for the paper and the fact that all the trainings were done on CPU, but since the repo is on PyPI it's obviously intended for more than that.

I've made the code work, I've tested it on my data, it looks impressive compared to an MLP and I'd be willing to help clean the repo up with some discussion and a few PRs. Would you be up for that?

**Comment by KindXiaoming** [comment]
Sounds good Viktor! Thank you for trying on your data and finding the issues! Indeed because I did not pass the device argument to [this line](https://github.com/KindXiaoming/pykan/blob/6aed4d78c687601b018fa750bdb0fd95a7080c11/kan/KAN.py#L138), my GPU test was actually on CPU (oops!) so did not catch potential bugs. My understanding is that you've changed
* correctly pass device argument to constructor
* remove `torch.set_default_dtype(torch.float64)` from pykan/kan/__init__.py (if they want, users can specify this at the top of their python or notebooks files)
These both sound reasonable to me. Did you do something more?

**Comment by viktor-ktorvi** [comment]
A few more `device=device` (or `device=self.device`) args needed to be passed:
* in [this line](https://github.com/KindXiaoming/pykan/blob/6aed4d78c687601b018fa750bdb0fd95a7080c11/kan/KANLayer.py#L174), I think
* and [this line](https://github.com/KindXiaoming/pykan/blob/4455ef70baaf275cae98666dfa74e83c5e0fee66/kan/spline.py#L58)

I think that was it. I should've kept note but I forgot.

**Comment by KindXiaoming** [comment]
Thank you, that's great! I can diff them if you go ahead PR :).
