### ISSUE TITLE
unexpected results

### ISSUE THREAD

**Issue by 321HG** [KindXiaoming/pykan#85]
Why do I get unexpected results when I run the code as per the example provided?
![1](https://github.com/KindXiaoming/pykan/assets/54180767/ab1ca1e3-d129-4cf4-ba47-9aa8b055f629)

**Comment by KindXiaoming** [comment]
that's very weird. well there's some code merge after the code was first released. This notebook should work at the time of first code release. If someone face the same problem, please help. If looks weird to me because if it's random guessing, the acc would be around 0.5. The fact that train acc and test acc are both 0.0 is quite suspicious, looking like a bug. Could you `print(correct, batch)` in the acc function? or maybe it helps to make sure `logit2 > logit1` and `y[i]` have the same dtype?
